version: 1
backend:
  phases:
    build:
      commands:
        - echo "Installing Python dependencies"
        - python -m pip install --upgrade pip
        - pip install -r covid_app/requirements.txt
        - echo "Backend build completed"
frontend:
  phases:
    preBuild:
      commands:
        - echo "Installing Python dependencies for frontend"
        - python -m pip install --upgrade pip
        - pip install -r covid_app/requirements.txt
    build:
      commands:
        - echo "Building FastAPI application"
        - echo "Build completed"
    postBuild:
      commands:
        - echo "Post build completed"
  artifacts:
    baseDirectory: .
    files:
      - '**/*'
  cache:
    paths:
      - .venv/**/*
      - __pycache__/**/*
